# Generated by Django 3.2.18 on 2023-05-23 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_accounts', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountsbyplanet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accounts.accountsbyplanet')),
            ],
        ),
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=10)),
                ('accountsbyplanet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accounts.accountsbyplanet')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_planets.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Tech', 'Tech'), ('Game', 'Game'), ('Music', 'Music'), ('Sprots', 'Sports'), ('Food', 'Food'), ('Hobby', 'Hobby')], max_length=20)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='planet/')),
                ('plan', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Primium')], max_length=10)),
                ('maximum_capacity', models.DecimalField(decimal_places=0, default=50, max_digits=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('Planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_planets.planet')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='planets/posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountbyplanet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accounts.accountsbyplanet')),
                ('emotion', models.ManyToManyField(related_name='emotion_post', through='app_planets.Emote', to='app_accounts.Accountsbyplanet')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_planets.planet')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='emote',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_planets.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='emotion',
            field=models.ManyToManyField(related_name='emotion_comment', through='app_planets.Emote', to='app_accounts.Accountsbyplanet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_planets.post'),
        ),
    ]
