# Generated by Django 3.2.18 on 2023-06-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='need_confirm',
            field=models.BooleanField(choices=[(True, 'Approval'), (False, 'Direct')], default=False),
        ),
    ]
