# Generated by Django 3.2.18 on 2023-06-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Game', 'Game'), ('Music', 'Music'), ('Sports', 'Sports'), ('Food', 'Food'), ('Hobby', 'Hobby')], max_length=20),
        ),
    ]
