# Generated by Django 3.2.18 on 2023-05-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_initial'),
        ('app_planets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='accountsbyplanet',
            new_name='accountbyplanet',
        ),
        migrations.RenameField(
            model_name='emote',
            old_name='accountsbyplanet',
            new_name='accountbyplanet',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_planets.post'),
        ),
        migrations.CreateModel(
            name='Recomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountbyplanet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accounts.accountbyplanet')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='app_planets.comment')),
            ],
        ),
    ]
