# Generated by Django 3.2.18 on 2023-06-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0002_alter_planet_category'),
        ('app_planets', '0002_auto_20230601_1409'),
    ]

    operations = [
    ]
