# Generated by Django 3.2.18 on 2023-05-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0002_auto_20230523_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='is_public',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=10),
        ),
    ]
