# Generated by Django 3.2.18 on 2023-06-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_initial'),
        ('app_planets', '0003_merge_20230604_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_items', to='app_planets.post')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_accounts.accountbyplanet')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_planets.post')),
                ('vote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_planets.voteitem')),
            ],
        ),
    ]
