# Generated by Django 3.2.18 on 2023-06-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0004_vote_voteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_planets.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(default='report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='recomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_planets.recomment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_planets.post'),
        ),
    ]
