# Generated by Django 3.2.18 on 2023-05-24 08:34

import app_planets.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0004_rename_termsofservices_termsofservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='planets/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=app_planets.models.Post.upload_to_directory),
        ),
    ]
