# Generated by Django 3.2.18 on 2023-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0004_vote_voteitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='account',
            new_name='accountbyplanet',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_item',
        ),
        migrations.AddField(
            model_name='vote',
            name='content',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VoteItem',
        ),
    ]
