# Generated by Django 3.2.18 on 2023-06-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0005_auto_20230607_1521'),
        ('app_planets', '0005_auto_20230607_1722'),
    ]

    operations = [
    ]
