# Generated by Django 3.2.18 on 2023-06-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0005_auto_20230607_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='accountbyplanet',
            new_name='voter',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='content',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.CreateModel(
            name='VoteTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_planets.post')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='votetopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_planets.votetopic'),
            preserve_default=False,
        ),
    ]
