# Generated by Django 3.2.18 on 2023-06-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0006_auto_20230607_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votetopic',
            old_name='content',
            new_name='title',
        ),
    ]
