# Generated by Django 3.2.18 on 2023-06-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0007_rename_content_votetopic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votetopic',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
