# Generated by Django 3.2.18 on 2023-06-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0006_merge_0005_auto_20230607_1521_0005_auto_20230607_1722'),
        ('app_planets', '0008_alter_votetopic_title'),
    ]

    operations = [
    ]
