# Generated by Django 3.2.18 on 2023-05-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbyplanet',
            old_name='backgounrd_image',
            new_name='background_image',
        ),
    ]
