# Generated by Django 3.2.18 on 2023-05-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsbyplanet',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to='app_accounts.Accountsbyplanet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
