# Generated by Django 3.2.18 on 2023-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbyplanet',
            name='admin_level',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'staff'), (3, 'admin')], default=1),
        ),
    ]
