# Generated by Django 3.2.18 on 2023-05-31 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_rename_backgounrd_image_accountbyplanet_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbyplanet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountbyplanet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
