# Generated by Django 3.2.18 on 2023-05-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0005_auto_20230524_1734'),
        ('app_accounts', '0003_auto_20230524_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accountsbyplanet',
            new_name='Accountbyplanet',
        ),
    ]
