# Generated by Django 3.2.18 on 2023-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0004_rename_accountsbyplanet_accountbyplanet'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbyplanet',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
